version: '3.8'

services:
  color-extraction-nim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: color-extraction-nim
    ports:
      - "8080:8080"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - PORT=8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nim-network

networks:
  nim-network:
    driver: bridge
